version: "3"
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - mynetwork
  redis:
    image: redis
    networks:
      - mynetwork
networks:
  mynetwork:


# version: "3"
# services:
#   fastapi:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "8000:8000"
#     networks:
#       - mynetwork
#   redis:
#     image: redis
#     networks:
#       mynetwork:
#         aliases:
#           - redis
# networks:
#   mynetwork:
