# version: '3'
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     depends_on:
#       - redis
#   redis:
#     image: redis
#     ports:
#       - 6379:6379


version: '3'
services:
  spark:
    build:
      context: .
    depends_on:
      - redis
  redis:
    image: redis
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]
    ports:
      - "6379:6379"
  dockerfile:
    build:
      context: .
    depends_on:
      - redis
    ports:
      - "8000:8000"